import "../globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Sidebar from "../components/Sidebar";
// import Controls from "../components/Controls";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import React from "react";
import Image from "next/image";

import MovieIcon from "/public/assets/icon-category-movie.svg";

const AuthLayout = ({ children }) => {
  return (
    <main className="flex min-h-screen max-w-[1000px] p-24">
      <div className="flex-col items-center justify-between ">
        <Image width="50" height="50" alt="bookmark" src={MovieIcon} />

        {children}
      </div>
    </main>
  );
};

export default AuthLayout;
