// "use client";

import "./globals.css";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import Sidebar from "../components/Sidebar";
// import Controls from "../components/Controls";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
// https://www.youtube.com/watch?v=Yokjzp91A4o
import React from "react";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";
import Dashboard from "@/components/Dashboard";
import Controls from "@/components/Controls";
import { ReduxProvider } from "@/components/ReduxProvider";
// import { useDispatch, useSelector } from "react-redux";
// import { setMedia, search } from "../../features/mediaSlice";
// import { AppDispatch } from "@/store/store";
// import { useEffect, useState, useCallback } from "react";

// const handle;
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  // const [loading, setLoading] = useState(true);
  // const dispatch = useDispatch<AppDispatch>();

  // const getData = useCallback(() => {
  //   dispatch(setMedia());
  //   setLoading(false);
  // }, [dispatch]);

  // useEffect(() => {
  //   getData();
  // }, [getData]);

  // if (loading) {
  //   return <p>Loading...</p>;
  // }

  return (
    <div className="flex flex-col bg-[#10141E] md:flex-row ">
      <Sidebar />
      <main className="flex min-h-screen flex-col items-center   p-[2em]">
        <ReduxProvider>
          <Controls />
          {children}
        </ReduxProvider>
      </main>
    </div>
  );
};

export default RootLayout;
